version: '3.8'

services:
  wincasa:
    build: .
    ports:
      - "8501:8501"  # Streamlit UI
      - "6006:6006"  # Phoenix monitoring
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - DB_CONNECTION_STRING=firebird+fdb://sysdba:masterkey@localhost:3050//app/WINCASA2022.FDB
    volumes:
      - ./WINCASA2022.FDB:/app/WINCASA2022.FDB:ro
      - ./logs:/app/logs
      - ./output:/app/output
      - /home/envs:/home/envs:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Optional: Standalone Phoenix monitoring
  phoenix:
    image: python:3.10-slim
    ports:
      - "6007:6006"  # Alternative Phoenix port
    command: >
      bash -c "
        pip install arize-phoenix &&
        python -c 'import phoenix as px; px.launch_app(port=6006, host=\"0.0.0.0\")'
      "
    restart: unless-stopped
    profiles:
      - monitoring

  # Optional: Nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - wincasa
    restart: unless-stopped
    profiles:
      - production

volumes:
  wincasa_data:
  logs: